[build]
  command = "npm run build"
  publish = "dist"

# Build environment variables
[build.environment]
  # Netlify provides these automatically:
  # BUILD_ID - unique ID for each build
  # COMMIT_REF - the commit hash
  # DEPLOY_ID - deployment ID
  # BRANCH - branch name
  # PULL_REQUEST - true if this is a pull request
  # NETLIFY - true when running on Netlify

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure .well-known files are served correctly
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

